---
- name: archive exists?
  stat:
    path: "{{ archive_destination_path }}/{{ archive_file_name }}"
  register: archive_exists

- include: checksums.yml

- name: fetch archive
  get_url:
    url: "{{ archive_url }}"
    dest: "{{ archive_destination_path }}"
    checksum: "{{ archive_checksum }}"
  register: archive_fetched
  when: "(archive_exists is not defined) or (not archive_checksum_match)"

- include: checksums.yml
  when: "archive_fetched is not defined"

- name: verify fetched archive
  fail:
    msg: "checksum did not match: {{ archive_calculated_checksum }}"
  when: "archive_fetched is not defined and not archive_checksum_match"

- name: extracted dir exists?
  stat:
    path: "{{ archive_destination_path }}/{{ archive_extracted_dir_name }}"
  register: archive_extracted_dir_exists

- name: unpack archive
  unarchive:
    src: "{{ archive_destination_path }}/{{ archive_file_name }}"
    dest: "{{ archive_destination_path }}"
    copy: no
    creates: "{{ archive_destination_path }}/{{ archive_extracted_dir_name }}"
