---
- include: checksums.yml

- name: make cache dir
  file:
    state: directory
    path: "{{ archive_cache_path }}"

- name: fetch archive
  get_url:
    url: "{{ archive_url }}"
    headers: "{{ archive_fetch_headers }}"
    dest: "{{ archive_cache_path }}"
    mode: "{{ archive_file_mode }}"
  register: archive_fetched
  when: "not archive.stat.exists or archive_checksum_match is not defined"
  tags:
  - archive

- include: checksums.yml
  when: archive_fetched is defined and not archive_fetched.skipped
  tags:
  - archive

- name: unpack archive
  unarchive:
    src: "{{ archive_cache_path }}/{{ archive_file_name }}"
    dest: "{{ archive_destination_path }}"
    copy: no
  register: archive_unpacked
  tags:
  - archive

- name: delete existing destination file
  file:
    path: "{{ archive_destination_path }}/{{ archive_destination_file_name }}"
    state: absent
  when: archive_destination_file_name != ''
  tags:
  - archive

- name: move extracted item
  command: mv {{ archive_destination_path }}/{{ archive_extracted_file_name }} {{ archive_destination_path }}/{{ archive_destination_file_name }}
  when: archive_destination_file_name != ''
  tags:
  - archive

- name: link extracted item
  file:
    state: link
    force: yes
    src: "{{ archive_destination_path }}/{{ archive_destination_file_name | default(archive_extracted_file_name) }}"
    dest: "{{ archive_destination_path }}/{{ archive_destination_link_name }}"
  when: archive_destination_link_name != ''
  tags:
  - archive
